Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition to frozen string literals by default.
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"
