services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle/gems
    environment:
      - RAILS_ENV=development

volumes:
  gem_cache:
